name: dotnet
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - id: setup-dotnet
        name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - id: cache
        name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
          key: ${{runner.os}}-nuget-${{hashFiles('**/packages.lock.json')}}
          restore-keys: |
            ${{runner.os}}-nuget-
      - id: restore
        name: Restore
        run: dotnet restore
      - id: build
        name: Build
        run: dotnet build --no-restore
  test:
    name: Test
    runs-on: ${{matrix.os}}
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - id: setup-dotnet
        name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - id: setup-headless-x11
        name: Setup headless X11
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libglfw3 libxrandr-dev libx11-dev libgl1-mesa-dev libegl1-mesa-dev
          sudo apt-get install -y --no-install-recommends xvfb libgl1-mesa-dri
      - id: cache
        name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
          key: ${{runner.os}}-nuget-${{hashFiles('**/packages.lock.json')}}
          restore-keys: |
            ${{runner.os}}-nuget-
      - id: restore
        name: Restore
        run: dotnet restore
      - id: build
        name: Build
        run: dotnet build --no-restore
      - id: start-xvfb
        name: Start Xvfb
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1280x720x24 > /dev/null 2>&1 &
      - id: test
        name: Test
        env:
          DISPLAY: ${{runner.os == 'Linux' && ':99.0' || '0'}}
        run: dotnet test --no-build
